let FULLSCREEN = false;
let DRAWALLFRAMES = false;

let ENDBOSS_REACHED = false;
let ENDBOSS_FIRST_CONTACT = false;
let ENDBOSS_IS_DEAD = false;
let GAME_IS_OVER = false;

const LEVEL_WIDTH = 719;
const BACKGROUNDREPEAT = 8;
const MAXBACKGROUNDWITH = LEVEL_WIDTH * BACKGROUNDREPEAT;
const OBJECT_LEVEL_END = MAXBACKGROUNDWITH - 800;
const CHARACTER_LEVEL_END = MAXBACKGROUNDWITH - 200;
