let SOUND_ON = false;
let MUSIC_ON = false;
let FULLSCREEN = false;
let DRAWALLFRAMES = false;

let ENDBOSS_REACHED = false;
let ENDBOSS_FIRST_CONTACT = false;
let ENDBOSS_IS_DEAD = false;
let GAME_IS_OVER = false;

let LEVEL_WIDTH = 719;
let BACKGROUNDREPEAT = 8;
//let MAXBACKGROUNDWITH = LEVEL_WIDTH * BACKGROUNDREPEAT;
let MAXBACKGROUNDWITH = 2000;
let OBJECT_LEVEL_END = MAXBACKGROUNDWITH - 800;
let CHARACTER_LEVEL_END = MAXBACKGROUNDWITH - 200;
