let SOUND_ON = true;
let ENDBOSS_REACHED = false;
let ENDBOSS_FIRST_CONTACT = false;
let LEVEL_WIDTH = 719;
let BACKGROUNDREPEAT = 8;
let MAXBACKGROUNDWITH = LEVEL_WIDTH * BACKGROUNDREPEAT;
let CHARACTER_LEVEL_END = MAXBACKGROUNDWITH - 200;